### ISSUE TITLE
Add support for controlling the allocator used for implicit coroutine created by some `co_yield std::ranges::elements_of(...)` expressions

### ISSUE THREAD

**Issue by lewissbaker** [lewissbaker/generator#5]
The implementation of `co_yield std::ranges::elements_of(x)` for types of `x` which are not `generator<Ref, X, Y>` ends up implicitly creating a new nested generator coroutine that is compatible with the parent coroutine and that iterates over `x` and successively `co_yields` its elements.

As this can end up creating a new coroutine it might end up heap-allocating state for that coroutine. The current implementation just always defaults to using `std::allocator` for that allocation (i.e. global operator new/delete).

Ideally we would provide some mechanism to allow users to have this allocation of the coroutine state performed by a custom allocator instead.

One option would be to have the coroutine/promise implicitly propagate whatever allocator was used (or would have been used if the allocation wasn't elided) to allocate the parent coroutine state. However, supporting this for stateful allocators would require storing a copy of the allocator in the promise, in addition to a copy of the allocator for the parameter (passed using `std::allocator_arg`) and a copy of the allocator stored by `promise_type::operator new()` so that it can be accessed by `promise_type::operator delete()`. The overhead of having to store this extra allocator copy would be incurred for all coroutines that use a stateful allocator, regardless of whether the coroutine body even uses this `co_yield elements_of(nonGenerator)` form.

Another alternative approach is to have the allocator explicitly propagated to the nested coroutine by passing it as a (mostly) optional parameter to `elements_of()`.
i.e. `co_yield std::ranges::elements_of(someRange, alloc)`

This allows coroutines that have a stateful allocator to propagate that allocator to the child coroutine explicitly, reusing the parameter copy, rather than having a separate copy of the allocator in the promise.
e.g.
```
template<typename Alloc>
generator<int> example(std::allocator_arg_t, Alloc alloc) {
  std::vector<int> x = ...;
  co_yield std::ranges::elements_of(x, alloc);
}
```

However, it would also be nice to have the allocator implicitly propagated in the case that it is stateless and not passed as an argument using `std::allocator_arg`.
e.g.
```
generator<int, int, my_stateless_allocator> example() {
  std::vector<int> x = ...;
  co_yield std::ranges::elements_of(x); // This should also use my_stateless_allocator
}
```

To avoid surprising behaviour in generic code that might otherwise depend on whether
the allocator is stateless or not, implicit propagation of the allocator should not be
performed for `std::allocator_arg`-provided allocators.
i.e. `co_yield std::ranges::elements_of(nonGenerator);` should be ill-formed if the allocator was provided by a `std::allocator_arg`.

**Comment by cor3ntin** [comment]
Fixed by #3
